export const VALID_MUTATIONS = { 
        SET_SESSIONS: "SET_SESSIONS",
        SET_SESSIONS_COLUMNS: "SET_SESSIONS_COLUMNS",
        SET_SESSIONS_SORT_BY: "SET_SESSIONS_SORT_BY",
        SET_SESSIONS_SORT_TYPE: "SET_SESSIONS_SORT_TYPE",
        SET_SESSIONS_SORT_ASC: "SET_SESSIONS_SORT_ASC",
        SET_SESSIONS_FILTER_BY: "SET_SESSIONS_FILTER_BY",
        SET_SESSIONS_FILTER_VALUE: "SET_SESSIONS_FILTER_VALUE",
        SET_GRAPH: "SET_GRAPH",
        DELETE_SESSION: "DELETE_SESSION",
        LOADING: "LOADING",
        SET_USER_PERM: "SET_USER_PERM"
}